/*
 * 006_stability_hardening.sql
 * Постоянное хранение изменяемых настроек, атомарное создание бронирования,
 * атомарная замена iCal-событий и исправление слишком широких RLS-политик.
 *
 * Применять после 001-005 в Supabase SQL Editor одним запуском.
 */

CREATE TABLE IF NOT EXISTS app_config (
  key        TEXT PRIMARY KEY,
  value      JSONB NOT NULL DEFAULT '{}'::jsonb,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

DROP TRIGGER IF EXISTS trg_app_config_updated_at ON app_config;
CREATE TRIGGER trg_app_config_updated_at
  BEFORE UPDATE ON app_config
  FOR EACH ROW EXECUTE FUNCTION fn_update_timestamp();

ALTER TABLE bookings
  ADD COLUMN IF NOT EXISTS extras_snapshot JSONB NOT NULL DEFAULT '[]'::jsonb;

CREATE TABLE IF NOT EXISTS admin_audit_log (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor       TEXT NOT NULL DEFAULT 'admin',
  method      VARCHAR(10) NOT NULL,
  path        TEXT NOT NULL,
  status_code INTEGER,
  ip          TEXT,
  user_agent  TEXT,
  details     JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_admin_audit_created_at
  ON admin_audit_log (created_at DESC);

/* Service role обходит RLS. Разрешающие FOR ALL-политики без TO небезопасны. */
DROP POLICY IF EXISTS cabins_service_all ON cabins;
DROP POLICY IF EXISTS prices_service_all ON prices;
DROP POLICY IF EXISTS extra_services_service_all ON extra_services;
DROP POLICY IF EXISTS guests_service_all ON guests;
DROP POLICY IF EXISTS bookings_service_all ON bookings;
DROP POLICY IF EXISTS bes_service_all ON booking_extra_services;
DROP POLICY IF EXISTS chat_service_all ON chat_logs;
DROP POLICY IF EXISTS "Allow guests to read their own chats" ON chat_logs;
DROP POLICY IF EXISTS guest_notes_service_all ON guest_notes;

DROP POLICY IF EXISTS cabins_public_read ON cabins;
CREATE POLICY cabins_public_read ON cabins
  FOR SELECT TO anon, authenticated
  USING (is_active = true);

DROP POLICY IF EXISTS prices_public_read ON prices;
CREATE POLICY prices_public_read ON prices
  FOR SELECT TO anon, authenticated
  USING (true);

DROP POLICY IF EXISTS extra_services_public_read ON extra_services;
CREATE POLICY extra_services_public_read ON extra_services
  FOR SELECT TO anon, authenticated
  USING (is_active = true);

ALTER TABLE app_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE admin_audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE external_calendar_sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE external_bookings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS app_config_public_all ON app_config;
DROP POLICY IF EXISTS audit_public_all ON admin_audit_log;
DROP POLICY IF EXISTS external_sources_public_all ON external_calendar_sources;
DROP POLICY IF EXISTS external_bookings_public_all ON external_bookings;

/*
 * Единственная атомарная операция создания гостя + бронирования.
 * Цена и снимок услуг передаются только доверенным Express-сервером;
 * anon/authenticated не имеют EXECUTE.
 */
CREATE OR REPLACE FUNCTION create_booking_atomic(
  p_cabin_id UUID,
  p_check_in DATE,
  p_check_out DATE,
  p_guest_name TEXT,
  p_guest_phone TEXT,
  p_guest_telegram TEXT,
  p_comment TEXT,
  p_guests_count INTEGER,
  p_total_price INTEGER,
  p_extras_snapshot JSONB DEFAULT '[]'::jsonb
)
RETURNS SETOF bookings
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_guest_id UUID;
  v_booking_id UUID;
BEGIN
  IF p_check_out <= p_check_in THEN
    RAISE EXCEPTION 'Дата выезда должна быть позже даты заезда';
  END IF;
  IF p_guests_count < 1 OR p_total_price < 0 THEN
    RAISE EXCEPTION 'Некорректные параметры бронирования';
  END IF;

  PERFORM pg_advisory_xact_lock(hashtext(p_cabin_id::text));
  IF EXISTS (
    SELECT 1 FROM external_bookings eb
    WHERE eb.cabin_id = p_cabin_id
      AND daterange(eb.check_in, eb.check_out, '[)') && daterange(p_check_in, p_check_out, '[)')
  ) THEN
    RAISE EXCEPTION 'Даты уже заняты во внешнем календаре';
  END IF;

  SELECT g.id INTO v_guest_id
  FROM guests AS g
  WHERE g.phone = p_guest_phone
  ORDER BY g.created_at ASC
  LIMIT 1
  FOR UPDATE;

  IF v_guest_id IS NULL THEN
    INSERT INTO guests (full_name, phone, telegram)
    VALUES (p_guest_name, p_guest_phone, NULLIF(p_guest_telegram, ''))
    RETURNING id INTO v_guest_id;
  ELSE
    UPDATE guests
    SET full_name = p_guest_name,
        telegram = NULLIF(p_guest_telegram, '')
    WHERE id = v_guest_id;
  END IF;

  INSERT INTO bookings (
    cabin_id, guest_id, check_in, check_out, guests_count,
    status, total_price, comment, extras_snapshot
  ) VALUES (
    p_cabin_id, v_guest_id, p_check_in, p_check_out, p_guests_count,
    'pending', p_total_price, NULLIF(p_comment, ''), COALESCE(p_extras_snapshot, '[]'::jsonb)
  ) RETURNING id INTO v_booking_id;

  RETURN QUERY SELECT b.* FROM bookings AS b WHERE b.id = v_booking_id;
END;
$$;

REVOKE ALL ON FUNCTION create_booking_atomic(UUID, DATE, DATE, TEXT, TEXT, TEXT, TEXT, INTEGER, INTEGER, JSONB)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION create_booking_atomic(UUID, DATE, DATE, TEXT, TEXT, TEXT, TEXT, INTEGER, INTEGER, JSONB)
  TO service_role;

/* Полная замена событий одного источника выполняется одной транзакцией. */
CREATE OR REPLACE FUNCTION replace_external_bookings(
  p_source_id UUID,
  p_events JSONB
)
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_source external_calendar_sources%ROWTYPE;
  v_count INTEGER := 0;
BEGIN
  SELECT * INTO v_source
  FROM external_calendar_sources
  WHERE id = p_source_id
  FOR UPDATE;

  IF NOT FOUND THEN RAISE EXCEPTION 'Источник календаря не найден'; END IF;

  PERFORM pg_advisory_xact_lock(hashtext(v_source.cabin_id::text));

  DELETE FROM external_bookings WHERE source_id = p_source_id;

  INSERT INTO external_bookings (
    source_id, cabin_id, external_uid, source_name, summary,
    check_in, check_out, raw_event, last_seen_at
  )
  SELECT
    v_source.id,
    v_source.cabin_id,
    event->>'uid',
    v_source.source_name,
    NULLIF(event->>'summary', ''),
    (event->>'check_in')::date,
    (event->>'check_out')::date,
    COALESCE(event->'raw_event', '{}'::jsonb),
    now()
  FROM jsonb_array_elements(COALESCE(p_events, '[]'::jsonb)) AS event
  WHERE event ? 'uid' AND event ? 'check_in' AND event ? 'check_out';

  GET DIAGNOSTICS v_count = ROW_COUNT;

  UPDATE external_calendar_sources
  SET last_synced_at = now(), last_sync_status = 'success', last_sync_error = NULL
  WHERE id = p_source_id;

  RETURN v_count;
END;
$$;

REVOKE ALL ON FUNCTION replace_external_bookings(UUID, JSONB)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION replace_external_bookings(UUID, JSONB) TO service_role;

COMMENT ON TABLE app_config IS 'Постоянные JSON-настройки, ранее находившиеся в src/data';
COMMENT ON COLUMN bookings.extras_snapshot IS 'Зафиксированные услуги и цены на момент бронирования';
COMMENT ON TABLE admin_audit_log IS 'Журнал изменяющих действий административной панели';

/* Атомарное сохранение списка iCal-источников одного домика. */
CREATE OR REPLACE FUNCTION save_external_calendar_sources(
  p_cabin_id UUID,
  p_sources JSONB
)
RETURNS SETOF external_calendar_sources
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  PERFORM pg_advisory_xact_lock(hashtext(p_cabin_id::text));

  DELETE FROM external_calendar_sources ecs
  WHERE ecs.cabin_id = p_cabin_id
    AND NOT EXISTS (
      SELECT 1
      FROM jsonb_array_elements(COALESCE(p_sources, '[]'::jsonb)) source
      WHERE source->>'id' = ecs.id::text
    );

  INSERT INTO external_calendar_sources (id, cabin_id, source_name, ical_url, is_active)
  SELECT
    COALESCE(NULLIF(source->>'id', '')::uuid, gen_random_uuid()),
    p_cabin_id,
    left(COALESCE(NULLIF(source->>'source_name', ''), 'Внешний источник'), 80),
    source->>'ical_url',
    COALESCE((source->>'is_active')::boolean, true)
  FROM jsonb_array_elements(COALESCE(p_sources, '[]'::jsonb)) source
  WHERE COALESCE(source->>'ical_url', '') <> ''
  ON CONFLICT (id) DO UPDATE SET
    source_name = EXCLUDED.source_name,
    ical_url = EXCLUDED.ical_url,
    is_active = EXCLUDED.is_active;

  RETURN QUERY
    SELECT * FROM external_calendar_sources ecs
    WHERE ecs.cabin_id = p_cabin_id
    ORDER BY ecs.created_at;
END;
$$;

REVOKE ALL ON FUNCTION save_external_calendar_sources(UUID, JSONB)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION save_external_calendar_sources(UUID, JSONB) TO service_role;

/* Домик, его фото, наполнение, теги и iCal-источники сохраняются одной транзакцией. */
CREATE OR REPLACE FUNCTION save_cabin_full(
  p_cabin_id UUID,
  p_name TEXT,
  p_description TEXT,
  p_base_price INTEGER,
  p_capacity INTEGER,
  p_is_active BOOLEAN,
  p_images JSONB,
  p_amenities JSONB,
  p_tags JSONB,
  p_sources JSONB
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_id UUID := COALESCE(p_cabin_id, gen_random_uuid());
  v_row cabins%ROWTYPE;
BEGIN
  IF length(trim(COALESCE(p_name, ''))) = 0 THEN RAISE EXCEPTION 'Название обязательно'; END IF;
  IF p_base_price < 0 OR p_capacity < 1 THEN RAISE EXCEPTION 'Некорректные цена или вместимость'; END IF;
  PERFORM pg_advisory_xact_lock(hashtext(v_id::text));

  IF EXISTS (SELECT 1 FROM cabins WHERE id = v_id) THEN
    UPDATE cabins SET
      name = left(trim(p_name), 255),
      description = COALESCE(p_description, ''),
      base_price = p_base_price,
      capacity = p_capacity,
      is_active = p_is_active,
      images_urls = ARRAY(SELECT image #>> '{}' FROM jsonb_array_elements(COALESCE(p_images, '[]'::jsonb)) image)
    WHERE id = v_id RETURNING * INTO v_row;
  ELSE
    INSERT INTO cabins (id, slug, name, description, base_price, capacity, is_active, images_urls)
    VALUES (
      v_id,
      'house-' || left(replace(v_id::text, '-', ''), 12),
      left(trim(p_name), 255),
      COALESCE(p_description, ''),
      p_base_price,
      p_capacity,
      p_is_active,
      ARRAY(SELECT image #>> '{}' FROM jsonb_array_elements(COALESCE(p_images, '[]'::jsonb)) image)
    ) RETURNING * INTO v_row;
  END IF;

  INSERT INTO app_config (key, value) VALUES ('amenities', jsonb_build_object(v_id::text, COALESCE(p_amenities, '[]'::jsonb)))
  ON CONFLICT (key) DO UPDATE SET value = jsonb_set(app_config.value, ARRAY[v_id::text], COALESCE(p_amenities, '[]'::jsonb), true);

  INSERT INTO app_config (key, value) VALUES ('cabin_tags', jsonb_build_object(v_id::text, COALESCE(p_tags, '[]'::jsonb)))
  ON CONFLICT (key) DO UPDATE SET value = jsonb_set(app_config.value, ARRAY[v_id::text], COALESCE(p_tags, '[]'::jsonb), true);

  PERFORM save_external_calendar_sources(v_id, COALESCE(p_sources, '[]'::jsonb));
  RETURN to_jsonb(v_row);
END;
$$;

REVOKE ALL ON FUNCTION save_cabin_full(UUID, TEXT, TEXT, INTEGER, INTEGER, BOOLEAN, JSONB, JSONB, JSONB, JSONB)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION save_cabin_full(UUID, TEXT, TEXT, INTEGER, INTEGER, BOOLEAN, JSONB, JSONB, JSONB, JSONB)
  TO service_role;
